version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hagne
      - POSTGRES_USER=hagne
      - POSTGRES_PASSWORD=hagne
  redis:
    iamge: redis:alpine
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A hagne beat & celery -A hagne beat & python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/hagne/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_NAME=hagne
      - DB_USER=hagne
      - DB_PASSWORD=hagne
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=your_secret
    depends_on:
      - db
      - redis
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/static
    ports:
      - 8001:8001
    depends_on:
      - web
volumes:
  static_volume: