version: '3'
services:
  redis:
    image: redis:alpine
  db:
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    environment:
      - DEBUG=False
      - DB_NAME=shop
      - DB_USER=shop
      - DB_PASSWORD=shop
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=0l-}$Jm?hRswBcz13S/"`R@PXhmXkj
    depends_on:
      - db
      - redis
      - celery
      - celery-beat
  celery:
    build: .
    restart: always
    command: celery -A hagne worker -l info
    environment:
      - REDIS_HOST=redis
      - DEBUG=False
      - DB_NAME=shop
      - DB_USER=shop
      - DB_PASSWORD=shop
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=0l-}$Jm?hRswBcz13S/"`R@PXhmXkj
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    restart: always
    command: celery -A hagne beat -l info
    environment:
      - REDIS_HOST=redis
      - DEBUG=False
      - DB_NAME=shop
      - DB_USER=shop
      - DB_PASSWORD=shop
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=0l-}$Jm?hRswBcz13S/"`R@PXhmXkj
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
