version: '3'
services:
  redis:
    image: redis:alpine
  db:
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - DB_NAME=shop
      - DB_USER=shop
      - DB_PASSWORD=shop
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=your_secret_key
    depends_on:
      - db
      - redis
      - celery
      - celery-beat
  celery:
    build: .
    restart: always
    command: celery -A hagne worker -l info
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  celery-beat:
    build: .
    restart: always
    command: celery -A hagne beat -l info
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/static
    ports:
      - 8001:8001
    depends_on:
      - web
volumes:
  static_volume:
