# Generated by Django 4.2.2 on 2023-06-28 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('ean', models.CharField(max_length=13)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('tax_rate', models.IntegerField()),
                ('product_category_tree', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(verbose_name=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
